name: Hello World
on:
  push:
    branches: 
      - main
  workflow_dispatch: 
    inputs:
      name_variable:
        description: 'Please enter the name variable'
        required: true
        default: 'Komal'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello Name
        run: echo "Hello ${{ github.event.inputs.name_variable }}"
