name: Hello World
on:
  push:
    branches: 
      - main
  workflow_dispatch: 
    inputs:
      name_variable:
        description: 'Please enter the name'
        default: 'Komal'
      sandwich_variable:
       description: 'Favourite sandwich'
       default: 'Cubano'

jobs:
  hello:
    runs-on: ubuntu-latest
    env:
      name_env_var: "Shiva"
    steps:
      - name: Print Hello Name
        run: echo "Hello ${{ inputs.name_variable }}"
      - name: Print Hello name in Env variable
        run: echo "Hello $name_env_var "
      - name: Print Favourite Sandwich 
        run: echo "${{ inputs.name_variable }}'s favourite sandwich is ${{ inputs.sandwich_variable }}"
      
